/**
 * Section registry. Each entry is matched against the RenderContext and, if
 * applicable, emitted into the resolved structure at its baseOrder slot.
 *
 * Order is purely numeric — fractional orders allow targeted insertions
 * (e.g. methodology variants) without renumbering the canonical anchors.
 */
import type { SectionRegistryEntry } from "../utils/applicability";

export const SECTION_REGISTRY: SectionRegistryEntry[] = [
  {
    id: "cover_page",
    baseOrder: 0,
    titleEn: "Cover",
    titlePt: "Capa",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "cover_letter",
    baseOrder: 1,
    titleEn: "Cover Letter",
    titlePt: "Carta de Apresentação",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "executive_summary",
    baseOrder: 2,
    titleEn: "Executive Summary",
    titlePt: "Sumário Executivo",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "scope_overview",
    baseOrder: 3,
    titleEn: "Scope Overview",
    titlePt: "Âmbito Geral",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },

  // ---- Family-specific narrative inserts (before phase breakdown) ----
  {
    id: "methodology",
    baseOrder: 3.1,
    titleEn: "Workplace Strategy",
    titlePt: "Estratégia de Workplace",
    subtitleEn: "Test-fit methodology and stakeholder alignment.",
    subtitlePt: "Metodologia de test-fit e alinhamento com stakeholders.",
    includedByDefault: true,
    tags: ["workplace"],
    applicability: { families: ["workplace"] },
    reason: "family:workplace",
  },
  {
    id: "methodology",
    baseOrder: 3.2,
    titleEn: "Coordination & Specialist Scope",
    titlePt: "Coordenação e Âmbito de Especialistas",
    includedByDefault: true,
    tags: ["hospitality"],
    applicability: { families: ["hospitality"] },
    reason: "family:hospitality",
  },
  {
    id: "methodology",
    baseOrder: 3.3,
    titleEn: "Engineering Coordination",
    titlePt: "Coordenação de Engenharias",
    includedByDefault: true,
    tags: ["healthcare"],
    applicability: { families: ["healthcare"] },
    reason: "family:healthcare",
  },

  {
    id: "phase_breakdown",
    baseOrder: 4,
    titleEn: "Phase Breakdown",
    titlePt: "Faseamento",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "deliverables",
    baseOrder: 5,
    titleEn: "Deliverables",
    titlePt: "Entregáveis",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "commercial_terms",
    baseOrder: 6,
    titleEn: "Commercial Terms",
    titlePt: "Condições Comerciais",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "payment_terms",
    baseOrder: 6.1,
    titleEn: "Payment Terms",
    titlePt: "Condições de Pagamento",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "exclusions",
    baseOrder: 7,
    titleEn: "Exclusions",
    titlePt: "Exclusões",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "assumptions",
    baseOrder: 7.5,
    titleEn: "Assumptions",
    titlePt: "Pressupostos",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "team",
    baseOrder: 8,
    titleEn: "Team",
    titlePt: "Equipa",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "schedule",
    baseOrder: 8.5,
    titleEn: "Schedule",
    titlePt: "Calendário",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
  {
    id: "signature",
    baseOrder: 9,
    titleEn: "Acceptance & Signature",
    titlePt: "Aceitação e Assinatura",
    includedByDefault: true,
    tags: [],
    reason: "canonical_anchor",
  },
];
