/**
 * Full HTML content for the PSA General Terms of Engagement appendix.
 * Rendered in a 2-column layout inside the appendix_general_terms block.
 * Source: PSA_GENERAL_TERMS_OF_ENGAGEMENT.docx (2026 draft).
 */
export const PSA_GENERAL_TERMS_HTML_EN = `
<h3>Article 1 – Definitions</h3>
<p>Unless otherwise stated in the Agreement, the following terms shall have the meanings assigned below:</p>
<p><strong>Agreement</strong> means the Proposal, Letter of Appointment, Fee Proposal, Purchase Order, these General Terms of Engagement and any schedules or appendices forming part thereof.</p>
<p><strong>Architect</strong> means Pedra Silva Arquitectos, including its directors, employees, consultants and authorised representatives.</p>
<p><strong>Client</strong> means the individual, company or entity appointing the Architect to perform the Services.</p>
<p><strong>Project</strong> means the development, building, workplace, hospitality, residential, healthcare or other project identified within the Agreement.</p>
<p><strong>Services</strong> means the professional architectural and related services expressly described within the Agreement.</p>
<p><strong>Additional Services</strong> means any services not expressly included within the agreed Scope of Services or which become necessary as a consequence of changes to the Project, Client instructions or circumstances beyond the Architect's reasonable control.</p>
<p><strong>Consultants</strong> means engineers, quantity surveyors, project managers, lighting designers, specialist designers, local consultants or any other consultants appointed by either the Client or the Architect.</p>
<p><strong>Contractor</strong> means the contractor or contractors appointed to construct, fit out or implement the Project.</p>
<p><strong>Deliverables</strong> means all drawings, reports, specifications, schedules, models, BIM information, presentations, calculations, visualisations, documentation and other information produced by the Architect as part of the Services.</p>
<p><strong>BIM Model</strong> means any Building Information Model produced by the Architect at the agreed Level of Development (LOD) for the purposes described within the Agreement.</p>
<p><strong>Change Request</strong> means any modification to the approved Project Brief, approved design, programme, procurement strategy, technical requirements or scope of the Project requested after approval of a design stage.</p>
<p><strong>Practical Completion</strong> means the stage at which the Contractor declares the works substantially complete in accordance with the relevant construction contract.</p>
<p><strong>Working Day</strong> means any day other than Saturdays, Sundays or public holidays applicable to the Architect's principal place of business.</p>

<h3>Article 2 – Appointment and Scope of Services</h3>
<p><strong>2.1 Appointment.</strong> The Client appoints Pedra Silva Arquitectos to perform the Services described within the Agreement, and the Architect accepts such appointment subject to these General Terms of Engagement.</p>
<p><strong>2.2 Scope of Services.</strong> The Architect shall perform only those Services expressly described within the Proposal or Agreement. No service shall be deemed included solely because it is customary, desirable or necessary unless specifically identified within the agreed Scope of Services. Any service not expressly included shall constitute an Additional Service.</p>
<p><strong>2.3 Standard of Care.</strong> The Architect shall exercise the reasonable skill, care and diligence expected of an appropriately qualified architectural practice experienced in projects of similar nature, complexity and scale. Nothing within the Agreement shall be construed as a warranty or guarantee that the Project will achieve any particular outcome, planning approval, certification, construction cost, programme or commercial objective.</p>
<p><strong>2.4 Deliverables.</strong> Unless otherwise agreed, Deliverables shall be issued in digital format. The Architect may determine the format, software platform and level of detail appropriate to each stage. Native editable files shall only be provided where expressly included within the Agreement.</p>
<p><strong>2.5 Excluded Services.</strong> Unless specifically stated otherwise, the following are excluded from the Architect's appointment: quantity surveying and cost consultancy; planning consultancy; legal advice; tax advice; geotechnical investigations; land or building surveys; structural assessments; contractor supervision; health and safety coordination; clerk of works services; commissioning management; specialist certifications; facilities management; post-occupancy evaluation.</p>
<p><strong>2.6 Reliance.</strong> The Architect shall be entitled to rely upon information, reports, surveys, drawings and documentation provided by the Client, Consultants, Contractors or other third parties without independently verifying their accuracy unless expressly appointed to do so.</p>

<h3>Article 3 – Client Responsibilities</h3>
<p><strong>3.1 Information.</strong> The Client shall provide, in a timely manner, all information reasonably necessary for the proper execution of the Services, including surveys, existing drawings, title information, planning documentation, landlord information, statutory approvals, operational requirements, design standards, brand guidelines, technical reports, utility information, environmental information and asbestos reports where applicable. The Architect shall not be responsible for delays or additional work arising from incomplete, inaccurate or late information.</p>
<p><strong>3.2 Decision Making.</strong> The Client shall nominate authorised representatives with authority to provide instructions and approve Deliverables. Instructions received from authorised representatives shall be deemed binding upon the Client.</p>
<p><strong>3.3 Timely Reviews.</strong> The Client shall review Deliverables promptly and communicate consolidated comments within the review periods identified in the Project Programme. Failure to issue comments within the agreed review period may require adjustments to the Project Programme.</p>
<p><strong>3.4 Approvals.</strong> The Client acknowledges that each approved design stage establishes the baseline for the subsequent phase of the Project. Changes requested following approval shall constitute Change Requests.</p>
<p><strong>3.5 Consultants.</strong> Where Consultants are appointed directly by the Client, the Client shall ensure they provide complete and coordinated information in accordance with the agreed programme. The Architect shall not be responsible for delays arising from Consultant performance.</p>
<p><strong>3.6 Access.</strong> The Client shall provide reasonable access to the Project site whenever required for performance of the Services. Where access is restricted or unavailable, the Architect shall not be liable for resulting delays.</p>
<p><strong>3.7 Construction Procurement.</strong> Unless expressly appointed otherwise, the Client shall remain responsible for contractor appointment, procurement strategy, contract administration, construction contracts, statutory submissions, authority applications and project financing.</p>

<h3>Article 4 – Architect's Responsibilities</h3>
<p><strong>4.1 General.</strong> The Architect shall perform the Services professionally and diligently in accordance with the Agreement.</p>
<p><strong>4.2 Coordination.</strong> Where included within the Scope of Services, the Architect shall coordinate information received from Consultants. Such coordination shall not transfer responsibility for Consultant design to the Architect. Each Consultant shall remain solely responsible for its own professional services.</p>
<p><strong>4.3 Construction Cost.</strong> Unless expressly appointed as Quantity Surveyor or Cost Consultant, the Architect shall not warrant or guarantee construction costs, contractor pricing, procurement savings, market conditions, inflation or the availability of labour or materials. Any cost estimates prepared by the Architect are indicative only.</p>
<p><strong>4.4 Programme.</strong> The Architect shall use reasonable endeavours to perform the Services in accordance with the agreed programme. The Architect shall not be liable for delays caused by Client decisions, Consultant delays, Contractor delays, statutory authorities, utility providers, procurement delays, force majeure events or circumstances beyond the Architect's reasonable control.</p>
<p><strong>4.5 Sustainability.</strong> Unless expressly appointed to provide certification services, the Architect shall not warrant the achievement of any environmental certification, sustainability rating or energy performance standard, including BREEAM, LEED, WELL, DGNB or equivalent systems.</p>
<p><strong>4.6 Regulatory Compliance.</strong> The Architect shall design in accordance with the regulations applicable to the agreed jurisdiction. For international projects requiring local adaptation, compliance with local regulations shall remain subject to review and confirmation by locally appointed consultants unless otherwise agreed.</p>

<h3>Article 5 – Design Development, Reviews and Approvals</h3>
<p><strong>5.1 Stage Approvals.</strong> The Services shall be performed in progressive stages as described within the Agreement. Approval of each stage authorises the Architect to proceed to the subsequent stage.</p>
<p><strong>5.2 Design Baseline.</strong> Upon approval of any design stage, all Deliverables issued at that stage shall become the approved Project Baseline. Subsequent modifications shall constitute Change Requests.</p>
<p><strong>5.3 Included Review Cycles.</strong> Unless otherwise stated within the Agreement, each design stage includes one formal presentation, one consolidated Client review and one coordinated revision. Additional review cycles shall constitute Additional Services.</p>
<p><strong>5.4 Consolidated Comments.</strong> Where multiple stakeholders are involved, the Client shall provide one coordinated set of comments. The Architect shall not be responsible for reconciling contradictory instructions received from different stakeholders.</p>
<p><strong>5.5 Late Changes.</strong> Changes requested after approval of a stage may require revised fees, revised programme, revised Deliverables and revised Consultant coordination.</p>
<p><strong>5.6 Abandoned Options.</strong> Alternative concepts, options or studies not selected by the Client shall not form part of the continuing Services.</p>

<h3>Article 6 – Programme and Project Delays</h3>
<p><strong>6.1 Programme.</strong> The Project Programme is prepared on the assumption of timely Client decisions, Consultant information, statutory approvals and access to the Project.</p>
<p><strong>6.2 Extensions of Time.</strong> The Architect shall be entitled to a reasonable extension of time where delays arise from circumstances outside its reasonable control, including late Client instructions, revised Project Brief, Change Requests, delayed Consultant information, authority reviews, contractor coordination, procurement changes and force majeure events.</p>
<p><strong>6.3 Suspension.</strong> Should the Client suspend the Project for more than fifteen (15) consecutive Working Days, the Architect may invoice all Services completed to date together with reasonable costs of maintaining project information, retaining key resources and remobilising the project. Where suspension exceeds ninety (90) consecutive days, the Architect reserves the right to reschedule the Project according to team availability; any resulting remobilisation costs, revised programme or additional work shall constitute an Additional Service.</p>
<p><strong>6.4 Client Delays.</strong> Where delays result from the Client, the Client's Consultants or Contractors, the Architect shall not be responsible for any resulting programme impacts and shall be entitled to recover any additional costs reasonably incurred.</p>
<p><strong>6.5 Acceleration.</strong> Should the Client request acceleration of the Project Programme, the Architect shall use reasonable endeavours to accommodate such request subject to resource availability. Any additional staffing, overtime, external consultant costs or other expenses necessary to achieve an accelerated programme shall constitute an Additional Service and shall be agreed in writing before implementation.</p>

<h3>Article 7 – Variations and Change Requests</h3>
<p><strong>7.1 General.</strong> The Services have been priced on the basis of the agreed Project Brief, Scope of Services, Project Programme and assumptions described within the Agreement. Any modification to these assumptions may constitute a Change Request.</p>
<p><strong>7.2 Change Requests.</strong> A Change Request includes, without limitation: changes to the Client's brief; changes to the approved design after stage approval; increases in project area or building height; additional buildings or project phases; increased room numbers or occupancy; revised workplace strategies, hotel operator or brand standards, authority or planning requirements, procurement strategy or technical standards; changes arising from third-party or landlord requirements; changes resulting from inaccurate information supplied by others; redesign resulting from Client instructions; and additional presentations or workshops beyond those included.</p>
<p><strong>7.3 Assessment.</strong> Upon receipt of a Change Request, the Architect shall notify the Client of its anticipated impact upon fees, programme, deliverables, consultant coordination and resource allocation. No Change Request shall be implemented until authorised by the Client, except where immediate action is necessary to avoid unreasonable delay.</p>
<p><strong>7.4 Additional Fees.</strong> Unless otherwise agreed, all Change Requests shall be treated as Additional Services and charged in accordance with the Architect's prevailing fee schedule or agreed hourly rates.</p>
<p><strong>7.5 Regulatory Changes.</strong> Changes in legislation, statutory requirements, building regulations, planning policies or authority requirements occurring after commencement of the Services shall constitute a Change Request unless expressly included within the original appointment.</p>

<h3>Article 8 – Additional Services</h3>
<p><strong>8.1 General.</strong> Additional Services comprise any professional services not expressly included within the agreed Scope of Services.</p>
<p><strong>8.2 Examples.</strong> Additional Services may include, without limitation: redesign following Client instruction; additional option or feasibility studies; additional planning submissions or appeals; value engineering or redesign following tender; contractor claims review; expert witness services; arbitration support; additional site inspections; procurement or furniture procurement assistance; FF&amp;E specification beyond the agreed scope; mock-up reviews; sample approvals; branding, graphics or signage design; specialist CGI or animation; additional BIM development; facilities management information; post-occupancy evaluations; and operational readiness support.</p>
<p><strong>8.3 Hourly Services.</strong> Where Additional Services cannot reasonably be priced in advance, they shall be undertaken on a time-charge basis in accordance with the Architect's prevailing hourly rates.</p>
<p><strong>8.4 Expenses.</strong> Reasonable expenses incurred in connection with Additional Services shall be reimbursed by the Client, including travel, accommodation, printing, courier services, specialist software licences and statutory application fees paid on behalf of the Client.</p>

<h3>Article 9 – Consultants and Third Parties</h3>
<p><strong>9.1 Consultant Appointments.</strong> Consultants may be appointed either directly by the Client or by the Architect where expressly stated in the Agreement. Unless otherwise agreed, each Consultant shall remain independently responsible for its own professional services.</p>
<p><strong>9.2 Coordination.</strong> Where consultant coordination forms part of the Architect's appointment, such coordination shall consist of reviewing and integrating consultant information into the architectural design. Coordination shall not constitute verification or acceptance of the technical accuracy of Consultant information.</p>
<p><strong>9.3 Local Consultants.</strong> For international projects, local consultants may be responsible for statutory submissions, local authority approvals, local code compliance, language adaptations and local technical standards. The Architect shall be entitled to rely upon such information.</p>
<p><strong>9.4 Third-Party Information.</strong> The Architect may rely upon information prepared by others, including measured, topographical and utility surveys, structural, geotechnical, asbestos or environmental reports, landlord information and existing drawings. The Architect shall not be responsible for errors arising from inaccurate or incomplete third-party information.</p>
<p><strong>9.5 Contractor Information.</strong> The Architect shall be entitled to rely upon information supplied by Contractors regarding shop drawings, fabrication information, specialist systems, product performance and installation methodologies. Responsibility for such information shall remain with the Contractor.</p>

<h3>Article 10 – Digital Information, BIM and Artificial Intelligence</h3>
<p><strong>10.1 Digital Deliverables.</strong> Unless otherwise agreed, Deliverables may be issued electronically. Electronic transmission shall constitute official issue.</p>
<p><strong>10.2 Cloud Collaboration.</strong> The Architect may use cloud-based collaboration platforms including Autodesk Construction Cloud, BIM 360, SharePoint, Microsoft Teams, Dropbox, Procore or equivalent systems. Documents uploaded to such platforms shall be deemed issued on the date of upload.</p>
<p><strong>10.3 BIM Models.</strong> Where BIM forms part of the Services, the Model shall be developed only to the agreed Level of Development (LOD). The BIM Model is intended as a design coordination tool and shall not be relied upon for fabrication, construction sequencing, temporary works or shop drawing production unless expressly agreed.</p>
<p><strong>10.4 Model Ownership.</strong> Ownership of all BIM Models remains with the Architect. The Client receives a non-exclusive licence to use the Models solely for the Project.</p>
<p><strong>10.5 Artificial Intelligence.</strong> The Architect may utilise artificial intelligence, computational design tools, automation software, scripting and other digital technologies in the performance of the Services. All Deliverables shall remain subject to professional review and quality assurance before issue. Internal workflows, prompts, scripts, algorithms and methodologies developed by the Architect remain the Architect's intellectual property.</p>
<p><strong>10.6 Cybersecurity.</strong> Neither party shall be liable for delays arising solely from cyber incidents, software failures or cloud service interruptions beyond their reasonable control.</p>

<h3>Article 11 – Intellectual Property</h3>
<p><strong>11.1 Ownership.</strong> All copyright, design rights, database rights, moral rights and other intellectual property rights in the Deliverables shall remain the property of the Architect.</p>
<p><strong>11.2 Licence.</strong> Upon payment of all fees due under the Agreement, the Client is granted a non-exclusive, non-transferable licence to use the Deliverables solely for constructing, operating, maintaining and altering the Project for which they were prepared.</p>
<p><strong>11.3 Restrictions.</strong> The Client shall not reuse the Deliverables for another project, alter them without professional review, permit third parties to modify them, or transfer them to another architect for completion of the Project, without the Architect's prior written consent, except where required by law.</p>
<p><strong>11.4 Reuse.</strong> Should the Client terminate the Architect's appointment and appoint another consultant, the Client may use completed Deliverables only upon full payment of all outstanding fees and subject to the successor consultant accepting responsibility for all subsequent work. The Architect accepts no liability for modifications made by others after termination.</p>
<p><strong>11.5 Publicity.</strong> Unless otherwise agreed in writing, the Architect may use drawings, images, photographs and descriptions of the Project for professional publications, awards, exhibitions, marketing, website content and promotional purposes following public completion of the Project. Where confidentiality obligations exist, publication shall occur only with the Client's consent or after such obligations expire.</p>

<h3>Article 12 – Confidentiality and Data Protection</h3>
<p><strong>12.1 Confidential Information.</strong> Both parties shall keep confidential all commercially sensitive information received during the Project and shall not disclose such information to third parties except where required for performance of the Services or by law.</p>
<p><strong>12.2 Exceptions.</strong> The confidentiality obligations shall not apply to information which is already publicly available, was lawfully known prior to disclosure, is received from a third party without breach of confidentiality, or is required to be disclosed by law or court order.</p>
<p><strong>12.3 GDPR.</strong> Each party shall comply with all applicable data protection legislation, including the General Data Protection Regulation (EU) 2016/679 ("GDPR") and any applicable national implementing legislation.</p>
<p><strong>12.4 Data Storage.</strong> The Architect may store Project information electronically using secure cloud-based systems operated by reputable service providers. The Client acknowledges that reasonable electronic security measures do not constitute an absolute guarantee against unauthorised access.</p>
<p><strong>12.5 Record Retention.</strong> Unless otherwise required by law, the Architect may archive or dispose of Project records after ten (10) years from completion of the Services.</p>

<h3>Article 13 – Tender, Procurement and Construction</h3>
<p><strong>13.1 Procurement Assistance.</strong> Where included within the Scope of Services, the Architect shall assist the Client during the procurement process by preparing tender documentation, responding to tender queries, participating in tender evaluations and making recommendations regarding the technical compliance of tender submissions. Unless expressly appointed otherwise, the Architect shall not act as procurement advisor, quantity surveyor or commercial manager.</p>
<p><strong>13.2 Contractor Appointment.</strong> The selection, appointment and contractual engagement of the Contractor shall remain the sole responsibility of the Client. Nothing within the Services shall constitute a recommendation or guarantee regarding the Contractor's financial standing, capability or future performance.</p>
<p><strong>13.3 Construction Administration.</strong> Where Construction Stage Services are included within the Agreement, the Architect shall periodically review the progress of the Works to assess, in general terms, whether they appear to be proceeding in accordance with the design intent expressed in the Contract Documents. Such reviews shall not constitute continuous supervision or inspection of the Works.</p>
<p><strong>13.4 Contractor Responsibilities.</strong> The Contractor shall remain solely responsible for construction methods, sequencing of the Works, temporary works, site safety, health and safety compliance, quality control, workmanship, material procurement, coordination of subcontractors, fabrication, installation, testing, commissioning and compliance with the construction contract. The Architect shall have no responsibility for the Contractor's means or methods of construction.</p>
<p><strong>13.5 Shop Drawings.</strong> Where shop drawings or specialist contractor drawings are submitted for review, the Architect's review shall be limited to assessing general conformity with the design intent. Such review shall not relieve the Contractor of responsibility for dimensions, quantities, fabrication methods, structural adequacy, coordination or installation.</p>
<p><strong>13.6 Samples and Mock-Ups.</strong> Review of material samples, prototypes or mock-ups shall not constitute acceptance of defective workmanship or relieve the Contractor from complying with the Contract Documents.</p>
<p><strong>13.7 Site Instructions.</strong> The Architect may issue architectural instructions, comments or clarification drawings where required to explain the design intent. Instructions affecting cost, programme or contractual obligations shall be issued through the Client or Project Manager unless otherwise agreed.</p>
<p><strong>13.8 Practical Completion.</strong> Unless expressly appointed as Contract Administrator under a separate agreement, the Architect shall not certify Practical Completion, Final Completion, payment certificates or contractual milestones.</p>

<h3>Article 14 – Site Visits</h3>
<p><strong>14.1 General.</strong> Site visits shall be undertaken only where included within the Scope of Services. Unless otherwise agreed, site visits shall be periodic and appropriate to the stage of construction.</p>
<p><strong>14.2 Purpose.</strong> Site visits are intended solely to observe general progress, review design implementation, identify apparent deviations from the design intent, respond to technical queries and participate in coordination meetings.</p>
<p><strong>14.3 No Continuous Supervision.</strong> The Client acknowledges that the Architect shall not provide continuous site supervision. The Architect shall not be responsible for detecting every defect, omission or non-compliance occurring during construction.</p>
<p><strong>14.4 Reporting.</strong> Where appropriate, the Architect may issue written observations or snagging reports following site visits. Such reports represent observations made at the time of inspection only and shall not constitute certification that the Works comply in every respect with the Contract Documents.</p>
<p><strong>14.5 Health and Safety.</strong> The Architect shall have no responsibility for site health and safety unless expressly appointed under a separate agreement to perform such duties.</p>

<h3>Article 15 – Fees, Payment and Expenses</h3>
<p><strong>15.1 Fees.</strong> The Client shall pay the Architect the fees set out in the Agreement. Unless otherwise stated, all fees are exclusive of applicable taxes, duties and VAT.</p>
<p><strong>15.2 Payment Terms.</strong> Invoices shall become due within the payment period specified in the Agreement. Where no payment period is specified, payment shall be due within thirty (30) calendar days from the invoice date.</p>
<p><strong>15.3 Stage Payments.</strong> Where fees are allocated by project stage, each stage shall become payable upon completion of the corresponding Deliverables or at the milestone defined within the Agreement, irrespective of whether the Client elects to proceed to subsequent stages.</p>
<p><strong>15.4 Additional Services.</strong> Additional Services shall be invoiced separately and shall not delay payment of the original agreed fees.</p>
<p><strong>15.5 Expenses.</strong> The Client shall reimburse reasonable project-related expenses, including travel, accommodation, subsistence, courier services, specialist printing, statutory fees paid on behalf of the Client and specialist software or platform costs required specifically for the Project.</p>
<p><strong>15.6 Late Payment.</strong> Where payment is not received by the due date, the Architect reserves the right to charge statutory interest or interest at a rate of 8% per annum above the European Central Bank base rate, whichever is permitted under the applicable law, together with reasonable costs incurred in recovering overdue amounts.</p>
<p><strong>15.7 Partial Payments.</strong> Acceptance of a partial payment shall not constitute acceptance of a reduced fee or waiver of any outstanding balance.</p>
<p><strong>15.8 Disputed Invoices.</strong> The Client shall notify the Architect of any disputed invoice within seven (7) calendar days of receipt, clearly identifying the disputed amount and the reasons for the dispute. Undisputed amounts shall remain payable in accordance with the agreed payment terms.</p>
<p><strong>15.9 Fee Adjustments for Long-Term Projects.</strong> Unless otherwise agreed in writing, where the duration of the Services exceeds twelve (12) months from the commencement date, the Architect reserves the right to adjust the fees applicable to the remaining unperformed Services to reflect increases in labour costs and inflation. Unless a different mechanism is stated in the Agreement, such adjustment shall be 4%, applied annually to the remaining unpaid stages only.</p>

<h3>Article 16 – Suspension and Termination</h3>
<p><strong>16.1 Suspension for Non-Payment.</strong> Where any invoice remains unpaid for more than fifteen (15) calendar days after written notice has been issued, the Architect may suspend performance of the Services until payment has been received. The Architect shall not be liable for any resulting delay to the Project.</p>
<p><strong>16.2 Suspension by the Client.</strong> Where the Client instructs suspension of the Project, Article 6 shall apply.</p>
<p><strong>16.3 Termination by the Client.</strong> The Client may terminate the Agreement by giving not less than fourteen (14) calendar days' written notice. The Client shall pay all Services performed to the termination date, all committed Consultant costs, all reimbursable expenses and all reasonable demobilisation costs.</p>
<p><strong>16.4 Termination by the Architect.</strong> The Architect may terminate the Agreement where invoices remain unpaid; the Client commits a material breach of the Agreement; the Client requests unlawful or unethical conduct; the Project is suspended for more than ninety (90) consecutive days; or circumstances arise preventing the proper performance of the Services.</p>
<p><strong>16.5 Rights Following Termination.</strong> Termination shall not affect accrued rights relating to payment, copyright, confidentiality, limitation of liability or dispute resolution.</p>

<h3>Article 17 – Professional Indemnity Insurance and Liability</h3>
<p><strong>17.1 Insurance.</strong> The Architect shall maintain Professional Indemnity Insurance throughout the performance of the Services with a limit of indemnity of EUR 500,000 per claim, or such other limit as may be maintained by the Architect from time to time. Evidence of insurance may be provided upon reasonable written request.</p>
<p><strong>17.2 Increased Insurance.</strong> Should the Client require a higher level of Professional Indemnity Insurance for the Project, the Architect shall use reasonable endeavours to obtain such additional cover, subject to insurer availability. Any additional premium, deductible, administrative cost or associated expense shall be borne entirely by the Client.</p>
<p><strong>17.3 Limitation of Liability.</strong> To the fullest extent permitted by applicable law, the total aggregate liability of the Architect arising out of or in connection with the Agreement, whether in contract, tort (including negligence), breach of statutory duty or otherwise, shall be limited to the amount recoverable under the Architect's applicable Professional Indemnity Insurance policy.</p>
<p><strong>17.4 Indirect Losses.</strong> Neither party shall be liable to the other for loss of profit, revenue, business opportunity or goodwill, or for consequential, indirect or punitive damages, except where such limitation is prohibited by applicable law.</p>
<p><strong>17.5 Proportionate Liability.</strong> The Architect shall be liable only for the proportion of loss directly attributable to its own negligence or breach of contract. The Architect shall not be responsible for losses arising from the acts or omissions of the Client, Contractors, Consultants or third parties.</p>
<p><strong>17.6 Time Limitation.</strong> No claim may be commenced against the Architect later than six (6) years after completion of the Services, unless a longer limitation period is required by the governing law.</p>

<h3>Article 18 – Force Majeure</h3>
<p><strong>18.1 Definition.</strong> Neither party shall be liable for any delay or failure to perform its obligations where such delay results from events beyond its reasonable control.</p>
<p><strong>18.2 Force Majeure Events.</strong> Force Majeure includes, without limitation: natural disasters; floods; earthquakes; fire; epidemics; pandemics; war; terrorism; civil unrest; sanctions; governmental restrictions; labour disputes; widespread utility failures; cyberattacks; failure of telecommunications infrastructure; interruption of cloud services; and transport disruption.</p>
<p><strong>18.3 Notification.</strong> The affected party shall notify the other as soon as reasonably practicable, identifying the nature of the event and its anticipated impact upon the Services.</p>
<p><strong>18.4 Programme.</strong> The Project Programme shall be adjusted to reflect delays arising directly from Force Majeure events. Neither party shall incur liability for such delay. The affected party may recover reasonable additional costs resulting from the delay.</p>

<h3>Schedule C – Standard Digital Deliverables</h3>
<p>Unless otherwise agreed, Deliverables shall be issued in PDF for drawings and reports; DWG where expressly included; IFC or RVT only where BIM Services have been commissioned; and native editable files only where specifically identified within the Agreement. The Architect retains ownership of all source files, scripts, templates, computational models and internal production tools.</p>
`;

export const PSA_GENERAL_TERMS_HTML_PT = PSA_GENERAL_TERMS_HTML_EN;
