/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiNotifyExpenseRouteImport } from './routes/api.notify-expense'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppHrIndexRouteImport } from './routes/_app.hr.index'
import { Route as AppCrmIndexRouteImport } from './routes/_app.crm.index'
import { Route as AppProjectsTimesheetRouteImport } from './routes/_app.projects.timesheet'
import { Route as AppProjectsResourcesRouteImport } from './routes/_app.projects.resources'
import { Route as AppProjectsMyTasksRouteImport } from './routes/_app.projects.my-tasks'
import { Route as AppProjectsInsightsRouteImport } from './routes/_app.projects.insights'
import { Route as AppProjectsGanttRouteImport } from './routes/_app.projects.gantt'
import { Route as AppProjectsForecastRouteImport } from './routes/_app.projects.forecast'
import { Route as AppProjectsFinancialsRouteImport } from './routes/_app.projects.financials'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppHrValorBoRouteImport } from './routes/_app.hr.valor-bo'
import { Route as AppHrSubsidioAlimentacaoRouteImport } from './routes/_app.hr.subsidio-alimentacao'
import { Route as AppHrResumoRouteImport } from './routes/_app.hr.resumo'
import { Route as AppHrMinhaFichaRouteImport } from './routes/_app.hr.minha-ficha'
import { Route as AppHrFeriasRouteImport } from './routes/_app.hr.ferias'
import { Route as AppHrDiasUteisRouteImport } from './routes/_app.hr.dias-uteis'
import { Route as AppHrBeneficiosRouteImport } from './routes/_app.hr.beneficios'
import { Route as AppHrAdminRouteImport } from './routes/_app.hr.admin'
import { Route as AppCrmPipelineRouteImport } from './routes/_app.crm.pipeline'
import { Route as AppCrmOpportunitiesRouteImport } from './routes/_app.crm.opportunities'
import { Route as AppCrmContactsRouteImport } from './routes/_app.crm.contacts'
import { Route as AppCrmCompaniesRouteImport } from './routes/_app.crm.companies'
import { Route as AppCrmAccountsRouteImport } from './routes/_app.crm.accounts'
import { Route as AppProjectsResourcesResourceIdRouteImport } from './routes/_app.projects.resources.$resourceId'
import { Route as AppHrColaboradorIdRouteImport } from './routes/_app.hr.colaborador.$id'
import { Route as AppCrmQuotesQuoteIdRouteImport } from './routes/_app.crm.quotes.$quoteId'
import { Route as AppCrmPipelineProposalIdRouteImport } from './routes/_app.crm.pipeline.$proposalId'
import { Route as AppCrmOpportunitiesOpportunityIdRouteImport } from './routes/_app.crm.opportunities.$opportunityId'
import { Route as AppCrmCompaniesCompanyIdRouteImport } from './routes/_app.crm.companies.$companyId'
import { Route as AppCrmAccountsAccountIdRouteImport } from './routes/_app.crm.accounts.$accountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiNotifyExpenseRoute = ApiNotifyExpenseRouteImport.update({
  id: '/api/notify-expense',
  path: '/api/notify-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHrRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppProjectsTimesheetRoute = AppProjectsTimesheetRouteImport.update({
  id: '/projects/timesheet',
  path: '/projects/timesheet',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsResourcesRoute = AppProjectsResourcesRouteImport.update({
  id: '/projects/resources',
  path: '/projects/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsMyTasksRoute = AppProjectsMyTasksRouteImport.update({
  id: '/projects/my-tasks',
  path: '/projects/my-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsInsightsRoute = AppProjectsInsightsRouteImport.update({
  id: '/projects/insights',
  path: '/projects/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsGanttRoute = AppProjectsGanttRouteImport.update({
  id: '/projects/gantt',
  path: '/projects/gantt',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsForecastRoute = AppProjectsForecastRouteImport.update({
  id: '/projects/forecast',
  path: '/projects/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsFinancialsRoute = AppProjectsFinancialsRouteImport.update({
  id: '/projects/financials',
  path: '/projects/financials',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppHrValorBoRoute = AppHrValorBoRouteImport.update({
  id: '/valor-bo',
  path: '/valor-bo',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrSubsidioAlimentacaoRoute =
  AppHrSubsidioAlimentacaoRouteImport.update({
    id: '/subsidio-alimentacao',
    path: '/subsidio-alimentacao',
    getParentRoute: () => AppHrRoute,
  } as any)
const AppHrResumoRoute = AppHrResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrMinhaFichaRoute = AppHrMinhaFichaRouteImport.update({
  id: '/minha-ficha',
  path: '/minha-ficha',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrFeriasRoute = AppHrFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrDiasUteisRoute = AppHrDiasUteisRouteImport.update({
  id: '/dias-uteis',
  path: '/dias-uteis',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrBeneficiosRoute = AppHrBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => AppHrRoute,
} as any)
const AppHrAdminRoute = AppHrAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppHrRoute,
} as any)
const AppCrmPipelineRoute = AppCrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmOpportunitiesRoute = AppCrmOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmContactsRoute = AppCrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmCompaniesRoute = AppCrmCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmAccountsRoute = AppCrmAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppProjectsResourcesResourceIdRoute =
  AppProjectsResourcesResourceIdRouteImport.update({
    id: '/$resourceId',
    path: '/$resourceId',
    getParentRoute: () => AppProjectsResourcesRoute,
  } as any)
const AppHrColaboradorIdRoute = AppHrColaboradorIdRouteImport.update({
  id: '/colaborador/$id',
  path: '/colaborador/$id',
  getParentRoute: () => AppHrRoute,
} as any)
const AppCrmQuotesQuoteIdRoute = AppCrmQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AppCrmRoute,
} as any)
const AppCrmPipelineProposalIdRoute =
  AppCrmPipelineProposalIdRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => AppCrmPipelineRoute,
  } as any)
const AppCrmOpportunitiesOpportunityIdRoute =
  AppCrmOpportunitiesOpportunityIdRouteImport.update({
    id: '/$opportunityId',
    path: '/$opportunityId',
    getParentRoute: () => AppCrmOpportunitiesRoute,
  } as any)
const AppCrmCompaniesCompanyIdRoute =
  AppCrmCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AppCrmCompaniesRoute,
  } as any)
const AppCrmAccountsAccountIdRoute = AppCrmAccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AppCrmAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/crm': typeof AppCrmRouteWithChildren
  '/hr': typeof AppHrRouteWithChildren
  '/api/notify-expense': typeof ApiNotifyExpenseRoute
  '/crm/accounts': typeof AppCrmAccountsRouteWithChildren
  '/crm/companies': typeof AppCrmCompaniesRouteWithChildren
  '/crm/contacts': typeof AppCrmContactsRoute
  '/crm/opportunities': typeof AppCrmOpportunitiesRouteWithChildren
  '/crm/pipeline': typeof AppCrmPipelineRouteWithChildren
  '/hr/admin': typeof AppHrAdminRoute
  '/hr/beneficios': typeof AppHrBeneficiosRoute
  '/hr/dias-uteis': typeof AppHrDiasUteisRoute
  '/hr/ferias': typeof AppHrFeriasRoute
  '/hr/minha-ficha': typeof AppHrMinhaFichaRoute
  '/hr/resumo': typeof AppHrResumoRoute
  '/hr/subsidio-alimentacao': typeof AppHrSubsidioAlimentacaoRoute
  '/hr/valor-bo': typeof AppHrValorBoRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/financials': typeof AppProjectsFinancialsRoute
  '/projects/forecast': typeof AppProjectsForecastRoute
  '/projects/gantt': typeof AppProjectsGanttRoute
  '/projects/insights': typeof AppProjectsInsightsRoute
  '/projects/my-tasks': typeof AppProjectsMyTasksRoute
  '/projects/resources': typeof AppProjectsResourcesRouteWithChildren
  '/projects/timesheet': typeof AppProjectsTimesheetRoute
  '/crm/': typeof AppCrmIndexRoute
  '/hr/': typeof AppHrIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/crm/accounts/$accountId': typeof AppCrmAccountsAccountIdRoute
  '/crm/companies/$companyId': typeof AppCrmCompaniesCompanyIdRoute
  '/crm/opportunities/$opportunityId': typeof AppCrmOpportunitiesOpportunityIdRoute
  '/crm/pipeline/$proposalId': typeof AppCrmPipelineProposalIdRoute
  '/crm/quotes/$quoteId': typeof AppCrmQuotesQuoteIdRoute
  '/hr/colaborador/$id': typeof AppHrColaboradorIdRoute
  '/projects/resources/$resourceId': typeof AppProjectsResourcesResourceIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/notify-expense': typeof ApiNotifyExpenseRoute
  '/': typeof AppIndexRoute
  '/crm/accounts': typeof AppCrmAccountsRouteWithChildren
  '/crm/companies': typeof AppCrmCompaniesRouteWithChildren
  '/crm/contacts': typeof AppCrmContactsRoute
  '/crm/opportunities': typeof AppCrmOpportunitiesRouteWithChildren
  '/crm/pipeline': typeof AppCrmPipelineRouteWithChildren
  '/hr/admin': typeof AppHrAdminRoute
  '/hr/beneficios': typeof AppHrBeneficiosRoute
  '/hr/dias-uteis': typeof AppHrDiasUteisRoute
  '/hr/ferias': typeof AppHrFeriasRoute
  '/hr/minha-ficha': typeof AppHrMinhaFichaRoute
  '/hr/resumo': typeof AppHrResumoRoute
  '/hr/subsidio-alimentacao': typeof AppHrSubsidioAlimentacaoRoute
  '/hr/valor-bo': typeof AppHrValorBoRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/financials': typeof AppProjectsFinancialsRoute
  '/projects/forecast': typeof AppProjectsForecastRoute
  '/projects/gantt': typeof AppProjectsGanttRoute
  '/projects/insights': typeof AppProjectsInsightsRoute
  '/projects/my-tasks': typeof AppProjectsMyTasksRoute
  '/projects/resources': typeof AppProjectsResourcesRouteWithChildren
  '/projects/timesheet': typeof AppProjectsTimesheetRoute
  '/crm': typeof AppCrmIndexRoute
  '/hr': typeof AppHrIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/crm/accounts/$accountId': typeof AppCrmAccountsAccountIdRoute
  '/crm/companies/$companyId': typeof AppCrmCompaniesCompanyIdRoute
  '/crm/opportunities/$opportunityId': typeof AppCrmOpportunitiesOpportunityIdRoute
  '/crm/pipeline/$proposalId': typeof AppCrmPipelineProposalIdRoute
  '/crm/quotes/$quoteId': typeof AppCrmQuotesQuoteIdRoute
  '/hr/colaborador/$id': typeof AppHrColaboradorIdRoute
  '/projects/resources/$resourceId': typeof AppProjectsResourcesResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/crm': typeof AppCrmRouteWithChildren
  '/_app/hr': typeof AppHrRouteWithChildren
  '/api/notify-expense': typeof ApiNotifyExpenseRoute
  '/_app/': typeof AppIndexRoute
  '/_app/crm/accounts': typeof AppCrmAccountsRouteWithChildren
  '/_app/crm/companies': typeof AppCrmCompaniesRouteWithChildren
  '/_app/crm/contacts': typeof AppCrmContactsRoute
  '/_app/crm/opportunities': typeof AppCrmOpportunitiesRouteWithChildren
  '/_app/crm/pipeline': typeof AppCrmPipelineRouteWithChildren
  '/_app/hr/admin': typeof AppHrAdminRoute
  '/_app/hr/beneficios': typeof AppHrBeneficiosRoute
  '/_app/hr/dias-uteis': typeof AppHrDiasUteisRoute
  '/_app/hr/ferias': typeof AppHrFeriasRoute
  '/_app/hr/minha-ficha': typeof AppHrMinhaFichaRoute
  '/_app/hr/resumo': typeof AppHrResumoRoute
  '/_app/hr/subsidio-alimentacao': typeof AppHrSubsidioAlimentacaoRoute
  '/_app/hr/valor-bo': typeof AppHrValorBoRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/financials': typeof AppProjectsFinancialsRoute
  '/_app/projects/forecast': typeof AppProjectsForecastRoute
  '/_app/projects/gantt': typeof AppProjectsGanttRoute
  '/_app/projects/insights': typeof AppProjectsInsightsRoute
  '/_app/projects/my-tasks': typeof AppProjectsMyTasksRoute
  '/_app/projects/resources': typeof AppProjectsResourcesRouteWithChildren
  '/_app/projects/timesheet': typeof AppProjectsTimesheetRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/hr/': typeof AppHrIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/crm/accounts/$accountId': typeof AppCrmAccountsAccountIdRoute
  '/_app/crm/companies/$companyId': typeof AppCrmCompaniesCompanyIdRoute
  '/_app/crm/opportunities/$opportunityId': typeof AppCrmOpportunitiesOpportunityIdRoute
  '/_app/crm/pipeline/$proposalId': typeof AppCrmPipelineProposalIdRoute
  '/_app/crm/quotes/$quoteId': typeof AppCrmQuotesQuoteIdRoute
  '/_app/hr/colaborador/$id': typeof AppHrColaboradorIdRoute
  '/_app/projects/resources/$resourceId': typeof AppProjectsResourcesResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/crm'
    | '/hr'
    | '/api/notify-expense'
    | '/crm/accounts'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/opportunities'
    | '/crm/pipeline'
    | '/hr/admin'
    | '/hr/beneficios'
    | '/hr/dias-uteis'
    | '/hr/ferias'
    | '/hr/minha-ficha'
    | '/hr/resumo'
    | '/hr/subsidio-alimentacao'
    | '/hr/valor-bo'
    | '/projects/$projectId'
    | '/projects/financials'
    | '/projects/forecast'
    | '/projects/gantt'
    | '/projects/insights'
    | '/projects/my-tasks'
    | '/projects/resources'
    | '/projects/timesheet'
    | '/crm/'
    | '/hr/'
    | '/projects/'
    | '/crm/accounts/$accountId'
    | '/crm/companies/$companyId'
    | '/crm/opportunities/$opportunityId'
    | '/crm/pipeline/$proposalId'
    | '/crm/quotes/$quoteId'
    | '/hr/colaborador/$id'
    | '/projects/resources/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/notify-expense'
    | '/'
    | '/crm/accounts'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/opportunities'
    | '/crm/pipeline'
    | '/hr/admin'
    | '/hr/beneficios'
    | '/hr/dias-uteis'
    | '/hr/ferias'
    | '/hr/minha-ficha'
    | '/hr/resumo'
    | '/hr/subsidio-alimentacao'
    | '/hr/valor-bo'
    | '/projects/$projectId'
    | '/projects/financials'
    | '/projects/forecast'
    | '/projects/gantt'
    | '/projects/insights'
    | '/projects/my-tasks'
    | '/projects/resources'
    | '/projects/timesheet'
    | '/crm'
    | '/hr'
    | '/projects'
    | '/crm/accounts/$accountId'
    | '/crm/companies/$companyId'
    | '/crm/opportunities/$opportunityId'
    | '/crm/pipeline/$proposalId'
    | '/crm/quotes/$quoteId'
    | '/hr/colaborador/$id'
    | '/projects/resources/$resourceId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/crm'
    | '/_app/hr'
    | '/api/notify-expense'
    | '/_app/'
    | '/_app/crm/accounts'
    | '/_app/crm/companies'
    | '/_app/crm/contacts'
    | '/_app/crm/opportunities'
    | '/_app/crm/pipeline'
    | '/_app/hr/admin'
    | '/_app/hr/beneficios'
    | '/_app/hr/dias-uteis'
    | '/_app/hr/ferias'
    | '/_app/hr/minha-ficha'
    | '/_app/hr/resumo'
    | '/_app/hr/subsidio-alimentacao'
    | '/_app/hr/valor-bo'
    | '/_app/projects/$projectId'
    | '/_app/projects/financials'
    | '/_app/projects/forecast'
    | '/_app/projects/gantt'
    | '/_app/projects/insights'
    | '/_app/projects/my-tasks'
    | '/_app/projects/resources'
    | '/_app/projects/timesheet'
    | '/_app/crm/'
    | '/_app/hr/'
    | '/_app/projects/'
    | '/_app/crm/accounts/$accountId'
    | '/_app/crm/companies/$companyId'
    | '/_app/crm/opportunities/$opportunityId'
    | '/_app/crm/pipeline/$proposalId'
    | '/_app/crm/quotes/$quoteId'
    | '/_app/hr/colaborador/$id'
    | '/_app/projects/resources/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiNotifyExpenseRoute: typeof ApiNotifyExpenseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/notify-expense': {
      id: '/api/notify-expense'
      path: '/api/notify-expense'
      fullPath: '/api/notify-expense'
      preLoaderRoute: typeof ApiNotifyExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/': {
      id: '/_app/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/projects/timesheet': {
      id: '/_app/projects/timesheet'
      path: '/projects/timesheet'
      fullPath: '/projects/timesheet'
      preLoaderRoute: typeof AppProjectsTimesheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/resources': {
      id: '/_app/projects/resources'
      path: '/projects/resources'
      fullPath: '/projects/resources'
      preLoaderRoute: typeof AppProjectsResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/my-tasks': {
      id: '/_app/projects/my-tasks'
      path: '/projects/my-tasks'
      fullPath: '/projects/my-tasks'
      preLoaderRoute: typeof AppProjectsMyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/insights': {
      id: '/_app/projects/insights'
      path: '/projects/insights'
      fullPath: '/projects/insights'
      preLoaderRoute: typeof AppProjectsInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/gantt': {
      id: '/_app/projects/gantt'
      path: '/projects/gantt'
      fullPath: '/projects/gantt'
      preLoaderRoute: typeof AppProjectsGanttRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/forecast': {
      id: '/_app/projects/forecast'
      path: '/projects/forecast'
      fullPath: '/projects/forecast'
      preLoaderRoute: typeof AppProjectsForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/financials': {
      id: '/_app/projects/financials'
      path: '/projects/financials'
      fullPath: '/projects/financials'
      preLoaderRoute: typeof AppProjectsFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/valor-bo': {
      id: '/_app/hr/valor-bo'
      path: '/valor-bo'
      fullPath: '/hr/valor-bo'
      preLoaderRoute: typeof AppHrValorBoRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/subsidio-alimentacao': {
      id: '/_app/hr/subsidio-alimentacao'
      path: '/subsidio-alimentacao'
      fullPath: '/hr/subsidio-alimentacao'
      preLoaderRoute: typeof AppHrSubsidioAlimentacaoRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/resumo': {
      id: '/_app/hr/resumo'
      path: '/resumo'
      fullPath: '/hr/resumo'
      preLoaderRoute: typeof AppHrResumoRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/minha-ficha': {
      id: '/_app/hr/minha-ficha'
      path: '/minha-ficha'
      fullPath: '/hr/minha-ficha'
      preLoaderRoute: typeof AppHrMinhaFichaRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/ferias': {
      id: '/_app/hr/ferias'
      path: '/ferias'
      fullPath: '/hr/ferias'
      preLoaderRoute: typeof AppHrFeriasRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/dias-uteis': {
      id: '/_app/hr/dias-uteis'
      path: '/dias-uteis'
      fullPath: '/hr/dias-uteis'
      preLoaderRoute: typeof AppHrDiasUteisRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/beneficios': {
      id: '/_app/hr/beneficios'
      path: '/beneficios'
      fullPath: '/hr/beneficios'
      preLoaderRoute: typeof AppHrBeneficiosRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/hr/admin': {
      id: '/_app/hr/admin'
      path: '/admin'
      fullPath: '/hr/admin'
      preLoaderRoute: typeof AppHrAdminRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/crm/pipeline': {
      id: '/_app/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AppCrmPipelineRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/opportunities': {
      id: '/_app/crm/opportunities'
      path: '/opportunities'
      fullPath: '/crm/opportunities'
      preLoaderRoute: typeof AppCrmOpportunitiesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/contacts': {
      id: '/_app/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof AppCrmContactsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/companies': {
      id: '/_app/crm/companies'
      path: '/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof AppCrmCompaniesRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/accounts': {
      id: '/_app/crm/accounts'
      path: '/accounts'
      fullPath: '/crm/accounts'
      preLoaderRoute: typeof AppCrmAccountsRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/projects/resources/$resourceId': {
      id: '/_app/projects/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/projects/resources/$resourceId'
      preLoaderRoute: typeof AppProjectsResourcesResourceIdRouteImport
      parentRoute: typeof AppProjectsResourcesRoute
    }
    '/_app/hr/colaborador/$id': {
      id: '/_app/hr/colaborador/$id'
      path: '/colaborador/$id'
      fullPath: '/hr/colaborador/$id'
      preLoaderRoute: typeof AppHrColaboradorIdRouteImport
      parentRoute: typeof AppHrRoute
    }
    '/_app/crm/quotes/$quoteId': {
      id: '/_app/crm/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/crm/quotes/$quoteId'
      preLoaderRoute: typeof AppCrmQuotesQuoteIdRouteImport
      parentRoute: typeof AppCrmRoute
    }
    '/_app/crm/pipeline/$proposalId': {
      id: '/_app/crm/pipeline/$proposalId'
      path: '/$proposalId'
      fullPath: '/crm/pipeline/$proposalId'
      preLoaderRoute: typeof AppCrmPipelineProposalIdRouteImport
      parentRoute: typeof AppCrmPipelineRoute
    }
    '/_app/crm/opportunities/$opportunityId': {
      id: '/_app/crm/opportunities/$opportunityId'
      path: '/$opportunityId'
      fullPath: '/crm/opportunities/$opportunityId'
      preLoaderRoute: typeof AppCrmOpportunitiesOpportunityIdRouteImport
      parentRoute: typeof AppCrmOpportunitiesRoute
    }
    '/_app/crm/companies/$companyId': {
      id: '/_app/crm/companies/$companyId'
      path: '/$companyId'
      fullPath: '/crm/companies/$companyId'
      preLoaderRoute: typeof AppCrmCompaniesCompanyIdRouteImport
      parentRoute: typeof AppCrmCompaniesRoute
    }
    '/_app/crm/accounts/$accountId': {
      id: '/_app/crm/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/crm/accounts/$accountId'
      preLoaderRoute: typeof AppCrmAccountsAccountIdRouteImport
      parentRoute: typeof AppCrmAccountsRoute
    }
  }
}

interface AppCrmAccountsRouteChildren {
  AppCrmAccountsAccountIdRoute: typeof AppCrmAccountsAccountIdRoute
}

const AppCrmAccountsRouteChildren: AppCrmAccountsRouteChildren = {
  AppCrmAccountsAccountIdRoute: AppCrmAccountsAccountIdRoute,
}

const AppCrmAccountsRouteWithChildren = AppCrmAccountsRoute._addFileChildren(
  AppCrmAccountsRouteChildren,
)

interface AppCrmCompaniesRouteChildren {
  AppCrmCompaniesCompanyIdRoute: typeof AppCrmCompaniesCompanyIdRoute
}

const AppCrmCompaniesRouteChildren: AppCrmCompaniesRouteChildren = {
  AppCrmCompaniesCompanyIdRoute: AppCrmCompaniesCompanyIdRoute,
}

const AppCrmCompaniesRouteWithChildren = AppCrmCompaniesRoute._addFileChildren(
  AppCrmCompaniesRouteChildren,
)

interface AppCrmOpportunitiesRouteChildren {
  AppCrmOpportunitiesOpportunityIdRoute: typeof AppCrmOpportunitiesOpportunityIdRoute
}

const AppCrmOpportunitiesRouteChildren: AppCrmOpportunitiesRouteChildren = {
  AppCrmOpportunitiesOpportunityIdRoute: AppCrmOpportunitiesOpportunityIdRoute,
}

const AppCrmOpportunitiesRouteWithChildren =
  AppCrmOpportunitiesRoute._addFileChildren(AppCrmOpportunitiesRouteChildren)

interface AppCrmPipelineRouteChildren {
  AppCrmPipelineProposalIdRoute: typeof AppCrmPipelineProposalIdRoute
}

const AppCrmPipelineRouteChildren: AppCrmPipelineRouteChildren = {
  AppCrmPipelineProposalIdRoute: AppCrmPipelineProposalIdRoute,
}

const AppCrmPipelineRouteWithChildren = AppCrmPipelineRoute._addFileChildren(
  AppCrmPipelineRouteChildren,
)

interface AppCrmRouteChildren {
  AppCrmAccountsRoute: typeof AppCrmAccountsRouteWithChildren
  AppCrmCompaniesRoute: typeof AppCrmCompaniesRouteWithChildren
  AppCrmContactsRoute: typeof AppCrmContactsRoute
  AppCrmOpportunitiesRoute: typeof AppCrmOpportunitiesRouteWithChildren
  AppCrmPipelineRoute: typeof AppCrmPipelineRouteWithChildren
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppCrmQuotesQuoteIdRoute: typeof AppCrmQuotesQuoteIdRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmAccountsRoute: AppCrmAccountsRouteWithChildren,
  AppCrmCompaniesRoute: AppCrmCompaniesRouteWithChildren,
  AppCrmContactsRoute: AppCrmContactsRoute,
  AppCrmOpportunitiesRoute: AppCrmOpportunitiesRouteWithChildren,
  AppCrmPipelineRoute: AppCrmPipelineRouteWithChildren,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppCrmQuotesQuoteIdRoute: AppCrmQuotesQuoteIdRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppHrRouteChildren {
  AppHrAdminRoute: typeof AppHrAdminRoute
  AppHrBeneficiosRoute: typeof AppHrBeneficiosRoute
  AppHrDiasUteisRoute: typeof AppHrDiasUteisRoute
  AppHrFeriasRoute: typeof AppHrFeriasRoute
  AppHrMinhaFichaRoute: typeof AppHrMinhaFichaRoute
  AppHrResumoRoute: typeof AppHrResumoRoute
  AppHrSubsidioAlimentacaoRoute: typeof AppHrSubsidioAlimentacaoRoute
  AppHrValorBoRoute: typeof AppHrValorBoRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
  AppHrColaboradorIdRoute: typeof AppHrColaboradorIdRoute
}

const AppHrRouteChildren: AppHrRouteChildren = {
  AppHrAdminRoute: AppHrAdminRoute,
  AppHrBeneficiosRoute: AppHrBeneficiosRoute,
  AppHrDiasUteisRoute: AppHrDiasUteisRoute,
  AppHrFeriasRoute: AppHrFeriasRoute,
  AppHrMinhaFichaRoute: AppHrMinhaFichaRoute,
  AppHrResumoRoute: AppHrResumoRoute,
  AppHrSubsidioAlimentacaoRoute: AppHrSubsidioAlimentacaoRoute,
  AppHrValorBoRoute: AppHrValorBoRoute,
  AppHrIndexRoute: AppHrIndexRoute,
  AppHrColaboradorIdRoute: AppHrColaboradorIdRoute,
}

const AppHrRouteWithChildren = AppHrRoute._addFileChildren(AppHrRouteChildren)

interface AppProjectsResourcesRouteChildren {
  AppProjectsResourcesResourceIdRoute: typeof AppProjectsResourcesResourceIdRoute
}

const AppProjectsResourcesRouteChildren: AppProjectsResourcesRouteChildren = {
  AppProjectsResourcesResourceIdRoute: AppProjectsResourcesResourceIdRoute,
}

const AppProjectsResourcesRouteWithChildren =
  AppProjectsResourcesRoute._addFileChildren(AppProjectsResourcesRouteChildren)

interface AppRouteChildren {
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppHrRoute: typeof AppHrRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsFinancialsRoute: typeof AppProjectsFinancialsRoute
  AppProjectsForecastRoute: typeof AppProjectsForecastRoute
  AppProjectsGanttRoute: typeof AppProjectsGanttRoute
  AppProjectsInsightsRoute: typeof AppProjectsInsightsRoute
  AppProjectsMyTasksRoute: typeof AppProjectsMyTasksRoute
  AppProjectsResourcesRoute: typeof AppProjectsResourcesRouteWithChildren
  AppProjectsTimesheetRoute: typeof AppProjectsTimesheetRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCrmRoute: AppCrmRouteWithChildren,
  AppHrRoute: AppHrRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsFinancialsRoute: AppProjectsFinancialsRoute,
  AppProjectsForecastRoute: AppProjectsForecastRoute,
  AppProjectsGanttRoute: AppProjectsGanttRoute,
  AppProjectsInsightsRoute: AppProjectsInsightsRoute,
  AppProjectsMyTasksRoute: AppProjectsMyTasksRoute,
  AppProjectsResourcesRoute: AppProjectsResourcesRouteWithChildren,
  AppProjectsTimesheetRoute: AppProjectsTimesheetRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiNotifyExpenseRoute: ApiNotifyExpenseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
