/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppValorBoRouteImport } from './routes/_app.valor-bo'
import { Route as AppResumoRouteImport } from './routes/_app.resumo'
import { Route as AppColaboradorIdRouteImport } from './routes/_app.colaborador.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppValorBoRoute = AppValorBoRouteImport.update({
  id: '/valor-bo',
  path: '/valor-bo',
  getParentRoute: () => AppRoute,
} as any)
const AppResumoRoute = AppResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradorIdRoute = AppColaboradorIdRouteImport.update({
  id: '/colaborador/$id',
  path: '/colaborador/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/resumo': typeof AppResumoRoute
  '/valor-bo': typeof AppValorBoRoute
  '/colaborador/$id': typeof AppColaboradorIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/resumo': typeof AppResumoRoute
  '/valor-bo': typeof AppValorBoRoute
  '/': typeof AppIndexRoute
  '/colaborador/$id': typeof AppColaboradorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/resumo': typeof AppResumoRoute
  '/_app/valor-bo': typeof AppValorBoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/colaborador/$id': typeof AppColaboradorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/resumo' | '/valor-bo' | '/colaborador/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/resumo' | '/valor-bo' | '/' | '/colaborador/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/resumo'
    | '/_app/valor-bo'
    | '/_app/'
    | '/_app/colaborador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/valor-bo': {
      id: '/_app/valor-bo'
      path: '/valor-bo'
      fullPath: '/valor-bo'
      preLoaderRoute: typeof AppValorBoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resumo': {
      id: '/_app/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof AppResumoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaborador/$id': {
      id: '/_app/colaborador/$id'
      path: '/colaborador/$id'
      fullPath: '/colaborador/$id'
      preLoaderRoute: typeof AppColaboradorIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppResumoRoute: typeof AppResumoRoute
  AppValorBoRoute: typeof AppValorBoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppColaboradorIdRoute: typeof AppColaboradorIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppResumoRoute: AppResumoRoute,
  AppValorBoRoute: AppValorBoRoute,
  AppIndexRoute: AppIndexRoute,
  AppColaboradorIdRoute: AppColaboradorIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
