
-- Seed PSA Workplace V1 master proposal blocks (idempotent by slug)
-- and link them to both Workplace / Office templates.

WITH new_blocks(slug, title, sort_order, content) AS (
  VALUES
  ('psa_workplace_v1_cover_letter', 'Cover Letter', 10,
   E'[Proposal Title / RFP Title]\n[Issue Date]\n\n[Client Name]\n\nDear Sirs,\n\nThank you for inviting us to submit our proposal for the {{project.name}} project.\n\nWe, the undersigned, offer to provide architectural and interior architecture design services for {{client.name}} in accordance with the information received from the client, the project management team and the project documentation made available to date.\n\nThis proposal sets out our understanding of the project, the scope of services to be provided, the proposed project phases, the expected deliverables, the fee structure and the conditions under which the services will be developed.\n\nWe hereby submit our detailed proposal for your review.\n\nWe also declare that our legal representative, Luís Pedra Silva, has the power to submit and sign the relevant documents, as well as to make, sign and do any other documents that may be necessary for the award, negotiation and signing of the agreement with {{client.name}}.\n\nIn representation of Pedra Silva Arquitectos,\n\nLuís Pedra Silva\nPartner\nSigned in Lisbon on [Issue Date]'),
  ('psa_workplace_v1_scope', 'Scope of Services & Project Description', 20,
   E'This proposal relates to the preparation of an interior architecture / workplace fit-out project for {{project.name}} and forms part of the response to the information, brief, RFP or project documentation provided by the client and its representatives.\n\nThe project is located at {{project.location}} and comprises approximately {{project.area}} of intervention area. The final area, floors, programme and scope of intervention shall be confirmed with the client prior to the start of the services.\n\nThe proposal has been prepared in accordance with the assumptions, base information and clarifications provided to date. The fees and programme have been calculated for the development of a workplace interior architecture project in accordance with contemporary best practice for fit-out projects and the quality standards of Pedra Silva Architects.\n\nUnless otherwise stated, the scope of services includes the architectural and interior architecture services described in the project phases below. Depending on the project, the scope may also include furniture selection, signage and wayfinding, workplace strategy, BIM coordination, procurement support and construction assistance.\n\nSpecialist consultants such as MEP, structural engineering, fire safety, lighting design, acoustics, AV, IT, sustainability, quantity surveying or other technical disciplines may be included, subcontracted through PSA or appointed directly by the client, as defined in the commercial schedules and consultant responsibility matrix.\n\nThe proposal does not include interventions outside the areas described above, interventions in the building façade or common areas, authority approval processes, licensing submissions, statutory fees, construction works, site supervision or project management unless specifically identified in this document.'),
  ('psa_workplace_v1_base_information', 'Base Information & Communication', 30,
   E'Before the start of the project, the design team must be provided with all information necessary for the development of the services. This information should include, but is not limited to:\n\n- the client''s expectations and project objectives;\n- the functional programme to be implemented;\n- headcount, organisational structure and workplace standards;\n- existing test-fits, workplace studies or feasibility studies where available;\n- architectural surveys, as-built drawings, site photographs and existing-condition information;\n- shell & core drawings and technical information;\n- landlord requirements and fit-out guidelines;\n- regulatory and technical constraints;\n- consultant information already developed or commissioned by the client.\n\nThe client should identify the relevant stakeholders and decision-makers at the start of the project so that the design team can obtain the necessary information and approvals in an organised manner. Delays in the provision of information, fragmented stakeholder comments or repeated changes to approved decisions may affect the project programme and fee basis.'),
  ('psa_workplace_v1_phases_overview', 'Project Phases — Overview', 40,
   E'Our services will be organised into the following distinct phases. The stage titles listed below are linked to the live stage records used throughout the proposal, Gantt, fee tables and payment schedules — editing a stage title anywhere in the quote builder updates every reference automatically.\n\n{{stages.numbered_list}}\n\nEach phase establishes a clear step in the development of the project. The start of each phase is dependent on the approval of the previous phase and on the provision of the necessary information by the client and relevant consultants.'),
  ('psa_workplace_v1_phase_01_workplace_strategy', 'Phase 01 — Workplace Strategy / Programme Definition', 50,
   E'## {{stage.1.title}}\n\nThe first stage of the project consists of defining the workplace strategy principles, validating the project programme and developing the initial planning studies required to establish the basis for the subsequent architectural development.\n\nThis phase ensures the client''s operational requirements, organisational structure, occupancy targets and workplace objectives are clearly defined and coordinated before progressing into the design stages of the project.\n\nAt the end of this phase, the programme, workplace strategy principles and test-fit studies should be reviewed and approved by the client as the baseline from which the project will subsequently be developed.\n\n**Key Tasks**\n- Review of all baseline information (organisational structure, headcount, workplace standards, technical reports, project constraints).\n- Identification of workplace requirements (workstation ratios, meeting rooms, collaboration / support spaces, focus rooms, social areas, storage).\n- Workplace strategy principles and occupancy analysis.\n- Programme validation studies and preliminary space calculation tables.\n- Test-fit layouts to assess feasibility of the proposed programme.\n- Departmental adjacency and circulation diagrams.\n- Building stacking / vertical distribution diagrams where applicable.\n- Coordination meetings and workshops with the client and stakeholders.\n\n**Deliverables**\n- Written programme definition and workplace strategy summary.\n- Space calculation and occupancy analysis tables.\n- Test-fit layouts with programme metrics.\n- Departmental adjacency and circulation diagrams.\n- Building stacking / vertical distribution studies where applicable.\n- Coordination presentations and workshop material.\n\n**Coordination & Approvals**\nClose interaction between the client''s operational representatives, workplace stakeholders, architecture team and project management. The approval of this phase is critical to establish a stable baseline for the subsequent Concept Design stage.\n\n**Phase Metadata**\n- Duration: {{stage.1.duration}}\n- Estimated hours: {{stage.1.hours}}\n- Phase fee: {{stage.1.fee}}'),
  ('psa_workplace_v1_phase_02_concept_design', 'Phase 02 — Concept Design', 60,
   E'## {{stage.2.title}}\n\nThe Concept Design phase develops the architectural and spatial direction of the project based on the approved programme, workplace strategy principles and test-fit studies developed during the previous phase.\n\nThe design team develops the fit-out layouts that will serve as the basis for the subsequent stages — workplace organisation, circulation principles, relationship between work areas and support spaces, and the general distribution of departments, teams and shared functions. The architectural approach for the interiors is also developed: general character, initial material direction, preliminary furniture principles and the visual language of the project.\n\nAt the end of this phase, the client should approve the general layout, spatial concept and architectural direction to be developed in the following phase.\n\n**Key Tasks**\n- Layout plans based on the approved programme and test-fit studies.\n- General spatial organisation, circulation principles and inter-department relationships.\n- Architectural concept for the interiors and initial materiality / atmosphere.\n- Preliminary furniture principles and workplace typologies.\n- Mood boards, reference images, diagrams and visual material.\n- Preliminary 3D views / CGI images where included.\n- Initial coordination with engineering, lighting, sustainability, signage, BIM or other specialist consultants where applicable.\n- Client presentations, design review sessions and incorporation of agreed comments.\n\n**Deliverables**\n- Concept Design presentation in digital PDF format.\n- General arrangement / functional plans for all floors.\n- Diagrams explaining programme distribution, circulation or workplace organisation.\n- Mood boards, reference images and material direction studies.\n- Preliminary furniture strategy.\n- Preliminary 3D views / CGI images, limited to the number defined in the proposal.\n- BIM model / IFC export at the agreed LOD, where BIM is included.\n\n**Coordination & Approvals**\nDeveloped in close coordination with the client and its stakeholders. Engineering / specialist consultants should provide initial comments where their input may affect the layout, ceiling strategy, technical requirements, local compliance or construction feasibility.\n\n**Phase Metadata**\n- Duration: {{stage.2.duration}}\n- Estimated hours: {{stage.2.hours}}\n- Phase fee: {{stage.2.fee}}'),
  ('psa_workplace_v1_phase_03_developed_design', 'Phase 03 — Developed / Schematic Design', 70,
   E'## {{stage.3.title}}\n\nThis phase refines and coordinates the approved Concept Design proposal in order to establish a coordinated basis for the subsequent Technical Design and procurement stages.\n\nArchitectural layouts, material principles, ceiling strategies, furniture coordination and spatial organisation are progressively developed in greater detail while integrating input from engineering systems, specialist consultants and operational requirements.\n\nAt the end of this phase, the principal design decisions, material directions and coordinated layouts should be approved by the client.\n\n**Key Tasks**\n- Refinement and coordination of the approved Concept Design proposal.\n- Coordinated architectural layouts and geometry.\n- Reflected ceiling plans and principal ceiling strategies.\n- Coordination with MEP, lighting, signage, acoustics, AV, sustainability and specialist consultants.\n- Schematic joinery and key architectural elements.\n- Material and finishes strategy.\n- Furniture layouts and workplace typologies.\n- BIM coordination and model development where applicable.\n- Multidisciplinary coordination workshops and client review sessions.\n\n**Deliverables**\n- General arrangement plans, typically 1:100.\n- Reflected ceiling plans, typically 1:100.\n- General sections and elevations.\n- Detailed key-area plans and sections (typically 1:50).\n- Schematic joinery / carpentry studies for principal elements.\n- Updated finishes and material presentation.\n- Updated furniture strategy and layouts.\n- Updated CGI images where applicable.\n- Preliminary consultant coordination drawings.\n- BIM model / IFC export at agreed development stage.\n\n**Coordination & Approvals**\nIntensive coordination between architecture, engineering and specialist consultants, project management, landlord teams and client stakeholders.\n\n**Phase Metadata**\n- Duration: {{stage.3.duration}}\n- Estimated hours: {{stage.3.hours}}\n- Phase fee: {{stage.3.fee}}'),
  ('psa_workplace_v1_phase_04_technical_design', 'Phase 04 — Technical Design', 80,
   E'## {{stage.4.title}}\n\nThe Technical Design phase develops the coordinated technical information required for contractor pricing, procurement, construction and implementation of the project.\n\n**Key Tasks**\n- Final coordination of the approved schematic proposal.\n- Coordinated technical architectural documentation.\n- Coordination of all engineering and specialist consultant information.\n- Detailed plans, sections, elevations and construction details.\n- Material, finishes and technical interface coordination.\n- Joinery / carpentry documentation.\n- Reflected ceiling plans and integrated systems.\n- Furniture coordination documentation and schedules.\n- BIM coordination and model development where applicable.\n- Technical review workshops and multidisciplinary coordination meetings.\n\n**Deliverables**\n- General arrangement plans, typically 1:100.\n- General finishes plans and reflected ceiling plans.\n- General sections and elevations.\n- Detailed plans, sections and elevations for key areas (typically 1:50).\n- Joinery / carpentry drawings (typically 1:20 / 1:10 where applicable).\n- Architectural construction details (typically 1:5).\n- Furniture layouts, identification plans and schedules where included.\n- Finishes schedules and material coordination documentation.\n- BIM model / IFC export at agreed LOD where applicable.\n- Tender / procurement documentation package for architectural scope.\n\n**Coordination & Approvals**\nIntensive multidisciplinary coordination. Local consultants should review the technical information to ensure compliance with local regulations and construction methodologies.\n\n**Phase Metadata**\n- Duration: {{stage.4.duration}}\n- Estimated hours: {{stage.4.hours}}\n- Phase fee: {{stage.4.fee}}'),
  ('psa_workplace_v1_phase_05_procurement', 'Phase 05 — Procurement / Tender Support', 90,
   E'## {{stage.5.title}}\n\nDuring the procurement process and up to the award of the contract, Pedra Silva Architects may provide technical assistance to the client and project management team in relation to the architectural project information issued for tender.\n\nThe responsibility for launching, managing and administering the construction tender normally lies with the client, project manager or procurement team unless specifically stated otherwise.\n\n**Key Tasks**\n- Clarification of doubts during preparation of the tender.\n- Written information and clarifications requested by tenderers, through the client or project management team.\n- Review of tender queries relating to the project documentation.\n- Assistance in evaluating technical variants or modifications submitted by bidders.\n- Coordination with quantity surveyors, project managers and specialist consultants.\n- Supplementary sketches or clarification information where required.\n\n**Deliverables**\n- Tender clarification responses and clarification log.\n- Supplementary sketches or written clarifications where required.\n- Technical input to the evaluation of contractor proposals where included.\n\n**Coordination & Approvals**\nUnless specifically included, this phase does not include tender administration, commercial negotiation, contractual documentation, contractor appointment procedures or procurement management.\n\n**Phase Metadata**\n- Duration: {{stage.5.duration}}\n- Estimated hours: {{stage.5.hours}}\n- Phase fee: {{stage.5.fee}}'),
  ('psa_workplace_v1_phase_06_construction_assistance', 'Phase 06 — Construction Assistance', 100,
   E'## {{stage.6.title}}\n\nDuring this phase the works are monitored through periodic meetings with the contractor, the client, the project management team and other consultants, with the aim of ensuring correct interpretation of the architectural project.\n\nConstruction Assistance is **not** a fixed deliverable package — it is an operational support service linked to the duration and demands of the construction period. For this reason, the service is structured as a **monthly retainer** based on the estimated level of architectural support required. The retainer should be reviewed periodically during construction to verify alignment between estimated and actual involvement.\n\n**Key Tasks**\n- Periodic site visits and/or remote coordination meetings where included.\n- Ongoing review of construction progress against the architectural design intent.\n- Responses to contractor requests for information.\n- Review of shop drawings, samples or mock-ups where applicable.\n- Preparation of clarification drawings or written information where required.\n- Coordination with contractor, project manager, site inspection team and specialist consultants.\n\n**Deliverables**\n- Written or drawn clarification information as required.\n- Responses to RFIs or contractor queries.\n- Site visit notes or meeting comments where applicable.\n- Review comments on samples, shop drawings or mock-ups where applicable.\n\n**Coordination & Approvals**\nConstruction Assistance does **not** include technical management, construction management, site supervision, safety coordination, quality control, contractor administration, or as-built drawings (unless specifically stated).\n\n**Phase Metadata**\n- Construction duration: {{stage.6.duration}}\n- Monthly retainer fee: {{stage.6.monthly_fee}}\n- Estimated monthly hours: {{stage.6.monthly_hours}}\n- Retainer review cycle: {{stage.6.retainer_review_cycle}}'),
  ('psa_workplace_v1_phase_07_close_out', 'Phase 07 — Close Out / Handover', 110,
   E'## {{stage.7.title}}\n\nDuring Close Out, the project team may assist the client and project management team in identifying outstanding architectural issues, supporting administrative close-out procedures and clarifying information required for the completion of the project.\n\n**Key Tasks**\n- Participation in final review meetings where applicable.\n- Support in identifying outstanding architectural items.\n- Review of design-related snagging issues where included.\n- Assistance with clarification of close-out information related to PSA''s scope.\n- Coordination with contractor, project manager and client facilities team where required.\n\n**Deliverables**\n- Written comments or clarification notes where required.\n- Close-out comments related to the architectural scope.\n- Review comments on contractor close-out information where applicable.\n\n**Coordination & Approvals**\nPreparation of technical data sheets, operation manuals, health and safety documentation, statutory close-out files, contractor handover documentation and as-built drawings are excluded from PSA''s scope unless specifically included.\n\n**Phase Metadata**\n- Duration: {{stage.7.duration}}\n- Estimated hours: {{stage.7.hours}}\n- Phase fee: {{stage.7.fee}}'),
  ('psa_workplace_v1_fee_proposal_intro', 'Fee Proposal', 120,
   E'Our fees are calculated based on the estimated time and resources required to develop the project and achieve the quality standards of Pedra Silva Architects.\n\nThe professional fees are divided by project stages and, where applicable, by construction assistance or other monthly retainer services. The detailed breakdown by stage — duration, estimated hours and stage fee — is provided in **Attachment II — Fee & Payment Schedule** and rendered live from the quote''s fee calculator and planner.\n\n**Notes**\n- All prices are exclusive of VAT.\n- Construction Assistance fees are charged monthly throughout the construction period.\n- If construction takes longer than indicated, the monthly amount will be applied to the additional time unless otherwise agreed.\n- If the organisation of the project phases is changed, reduced or extended, the fees may be subject to revision.'),
  ('psa_workplace_v1_payment_terms', 'Payment Terms', 130,
   E'The project design fees will be distributed over the design period and invoiced according to the payment schedule agreed with the client.\n\nUnless otherwise stated, the first invoice will be issued at the start of the project. Payment terms shall be [30 / 60] days from the date of invoice, unless otherwise agreed. The payment schedule is included as **Attachment II — Fee & Payment Schedule**. Should additional fees be required, these will be presented to the client for approval in writing before the additional work commences and will be billed separately.'),
  ('psa_workplace_v1_timeline', 'Timeline', 140,
   E'The project start date is defined as the date on which the agreement is signed and the initial payment is made, unless otherwise agreed.\n\nThe duration of each project stage and the project schedule are defined in the project programme included as **Attachment I — Project Programme / Gantt Chart**. The start of each phase is dependent on the client''s approval of the previous phase and on the information the client must provide. Deadlines may need to be adjusted in light of new information, changes to the brief, extended approval periods, consultant delays or unforeseen situations.'),
  ('psa_workplace_v1_additional_services', 'Additional Services', 150,
   E'If, during the course of the project, any additional services or work not described in this proposal are required, Pedra Silva Architects will inform the client and propose either a change to the general fees or additional fees, depending on the type and duration of the additional work.\n\nAdditional services may include, but are not limited to: changes to scope or area, increased complexity, work related to previously approved stages, late changes affecting the programme, additional meetings or presentation material, additional CGI images, additional BIM requirements, extended construction assistance, post-occupancy services.\n\nHourly rates for additional work shall be defined in the commercial schedule or general conditions.'),
  ('psa_workplace_v1_exclusions', 'Architecture Services Excluded', 160,
   E'Unless specifically stated otherwise, the following services are excluded from this proposal:\n\n- VAT at the legal rate in force.\n- Travel, accommodation, meals or other expenses outside the agreed project location.\n- Topographical, architectural, geotechnical or other surveys.\n- Design stages other than those described in this proposal.\n- Authority fees, taxes or statutory payments.\n- Licensing submissions or authority approval processes unless specifically included.\n- Engineering, landscape and other consultant services unless specifically included.\n- Fire safety, acoustics, AV, IT, security, sustainability or other specialist consultancy unless specifically included.\n- Project management or construction management.\n- Site supervision or inspection.\n- Health and safety coordination.\n- Contractor administration or tender administration unless specifically included.\n- Shop drawings or contractor fabrication drawings.\n- Quality control of construction.\n- As-built drawings.\n- Operation and maintenance manuals.\n- Technical data sheets and contractor handover files.\n- Physical models or mock-ups.\n- Marketing drawings, commercial CGI images or sales material.\n- 3D images beyond the number specifically included.\n- Any other services not specified in this proposal.'),
  ('psa_workplace_v1_validity', 'Validity and Acceptance', 170,
   E'This proposal is valid for a period of [30 / 60] days from the date of issue.\n\nWe hope this proposal meets your expectations and remain available to answer any questions you may have. If you accept this proposal, please sign and return this document to us.\n\nKind regards,\n\nLuís Pedra Silva\nPartner / Director\n\n---\n\n**Term of Acceptance**\n\nI accept this proposal under the terms described above.\n\nDate: ____ of ______________________ [Year]\nLegal representative of the client:\nSignature: _______________________________________________'),
  ('psa_workplace_v1_attachment_i_gantt', 'Attachment I — Project Programme / Gantt Chart', 180,
   E'This attachment contains the project programme and indicative timing for each phase of work. The programme is generated from the PSA Hub quote planning / Gantt tool and includes phase sequence, durations, start/end dates, dependencies, key client approval milestones, and the construction window where applicable.\n\nLive content: {{attachment.gantt}}'),
  ('psa_workplace_v1_attachment_ii_fees', 'Attachment II — Fee & Payment Schedule', 190,
   E'This attachment contains the detailed fee breakdown and payment schedule for the project. Live content is generated from the quote fee calculator, planner and payment schedule:\n\n- estimated hours from quote allocations (by role / rank, not by named staff);\n- phase fees from the fee calculator;\n- monthly retainer values from the construction assistance fee model;\n- payment schedule, separated into Design Stages and Construction Stage;\n- architecture and external services billed together or separately, per the quote''s billing mode.\n\nLive content: {{attachment.fee_payment_schedule}}'),
  ('psa_workplace_v1_attachment_iii_general_conditions', 'Attachment III — General Conditions', 200,
   E'This attachment contains the general contractual conditions applicable to this proposal: scope basis, client responsibilities, information requirements, approvals and sign-off process, changes and additional services, payment terms, reimbursable expenses, intellectual property, insurance, exclusions, suspension or delay provisions, VAT, consultant inclusions, BIM status and CGI count.\n\nThe general conditions form an integral part of the agreement between Pedra Silva Architects and the client.')
)
INSERT INTO public.proposal_blocks (
  title, slug, language, block_type, visibility,
  project_type_tags, service_type_tags,
  default_content, sort_order, is_active
)
SELECT
  nb.title, nb.slug, 'en'::text, 'editable_text'::proposal_block_type, 'client'::proposal_block_visibility,
  ARRAY['office']::text[], ARRAY['interior_architecture','workplace']::text[],
  nb.content, nb.sort_order, true
FROM new_blocks nb
WHERE NOT EXISTS (
  SELECT 1 FROM public.proposal_blocks pb WHERE pb.slug = nb.slug AND pb.language = 'en'
);

-- Link the workplace blocks to both Workplace / Office templates.
INSERT INTO public.quote_template_blocks (template_id, proposal_block_id, block_title, sort_order, required)
SELECT
  qt.id,
  pb.id,
  pb.title,
  pb.sort_order,
  true
FROM public.proposal_blocks pb
CROSS JOIN public.quote_templates qt
WHERE pb.slug LIKE 'psa_workplace_v1_%'
  AND pb.language = 'en'
  AND qt.name IN ('Workplace / Office — Large', 'Workplace / Office — Small')
  AND NOT EXISTS (
    SELECT 1 FROM public.quote_template_blocks qtb
    WHERE qtb.template_id = qt.id AND qtb.proposal_block_id = pb.id
  );
