ALTER TABLE public.quote_stages
  ADD COLUMN IF NOT EXISTS bill_to_client BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS markup_pct NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE public.pm_stages
  ADD COLUMN IF NOT EXISTS bill_to_client BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS markup_pct NUMERIC NOT NULL DEFAULT 0;